!del Done.txt
set print elements 0
set print repeats 0
set pagination off
target remote localhost:3333
load
break 57
continue
set $j=0
while($j<I_LOOP)
    break gdb_anchor
    continue
    n
    n
    eval "set logging file %i.txt", $j
    set logging on
    print /z *res
    print /z *(res+1)
    print /z *(res+2)
    print /z *(res+3)
    print /z *(res+4)
    print /z *(res+5)
    print /z *(res+6)
    print /z *(res+7)
    print /z *(res+8)
    print /z *(res+9)
    print /z *(res+10)
    print /z *(res+11)
    print /z *(res+12)
    print /z *(res+13)
    print /z *(res+14)
    print /z *(res+15)
    print /z *(res+16)
    print /z *(res+17)
    print /z *(res+18)
    print /z *(res+19)
    print /z *(res+20)
    print /z *(res+21)
    print /z *(res+22)
    print /z *(res+23)
    print /z *(res+24)
    print /z *(res+25)
    print /z *(res+26)
    print /z *(res+27)
    print /z *(res+28)
    print /z *(res+29)
    print /z *(res+30)
    print /z *(res+31)
    print /z *(res+32)    
    print /z *(res+33)
    print /z *(res+34)
    print /z *(res+35)
    print /z *(res+36)
    print /z *(res+37)
    print /z *(res+38)
    print /z *(res+39)
    print /z *(res+40)
    print /z *(res+41)
    print /z *(res+42)
    print /z *(res+43)
    print /z *(res+44)
    print /z *(res+45)
    print /z *(res+46)
    print /z *(res+47)
    print /z *(res+48)
    print /z *(res+49)
    print /z *(res+50)
    print /z *(res+51)
    print /z *(res+52)
    print /z *(res+53)
    print /z *(res+54)
    print /z *(res+55)
    print /z *(res+56)
    print /z *(res+57)
    print /z *(res+58)
    print /z *(res+59)
    print /z *(res+60)
    print /z *(res+61)
    print /z *(res+62)
    print /z *(res+63)
    print /z *(res+64)
    print /z *(res+65)
    print /z *(res+66)
    print /z *(res+67)
    print /z *(res+68)
    print /z *(res+69)
    print /z *(res+70)
    print /z *(res+71)
    print /z *(res+72)
    print /z *(res+73)
    print /z *(res+74)
    print /z *(res+75)
    print /z *(res+76)
    print /z *(res+77)
    print /z *(res+78)
    print /z *(res+79)
    print /z *(res+80)
    print /z *(res+81)
    print /z *(res+82)
    print /z *(res+83)
    print /z *(res+84)
    print /z *(res+85)
    print /z *(res+86)
    print /z *(res+87)
    print /z *(res+88)
    print /z *(res+89)
    print /z *(res+90)
    print /z *(res+91)
    print /z *(res+92)
    print /z *(res+93)
    print /z *(res+94)
    print /z *(res+95)
    print /z *(res+96)
    print /z *(res+97)
    print /z *(res+98)
    print /z *(res+99)
    print /z *(res+100)
    print /z *(res+101)
    print /z *(res+102)
    print /z *(res+103)
    print /z *(res+104)
    print /z *(res+105)
    print /z *(res+106)
    print /z *(res+107)
    print /z *(res+108)
    print /z *(res+109)
    print /z *(res+110)
    print /z *(res+111)
    print /z *(res+112)
    print /z *(res+113)
    print /z *(res+114)
    print /z *(res+115)
    print /z *(res+116)
    print /z *(res+117)
    print /z *(res+118)
    print /z *(res+119)
    print /z *(res+120)
    print /z *(res+121)
    print /z *(res+122)
    print /z *(res+123)
    print /z *(res+124)
    print /z *(res+125)
    print /z *(res+126)
    print /z *(res+127)

    set logging off
    set $j=$j+1
end
break 76
continue
set logging file Done.txt
set logging on
set logging off

continue